-- AlterTable
ALTER TABLE `Tag` ADD COLUMN `status` ENUM('ACCEPTED', 'PENDING', 'DENIED') NOT NULL DEFAULT 'ACCEPTED',
    ADD COLUMN `suggestorId` INTEGER NULL;

-- AddForeignKey
ALTER TABLE `Tag` ADD CONSTRAINT `Tag_suggestorId_fkey` FOREIGN KEY (`suggestorId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
